### ISSUE TITLE
nDPI 1.7.1 error

### ISSUE THREAD

**Issue by hichul** [caesar0301/pcapdpi#2]
Hi 
I have using pcapdpi  in nDPI 1.5.1 
It works great. 
I upgrade to nDPI 1.7.1 and try to use pcapdpi but when I to compile there is error

-------
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_typedefs.h:124:8: error: redefinition of ‘struct ndpi_ethhdr’
linux_compat.h:46:8: note: originally defined here
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_typedefs.h:188:8: error: redefinition of ‘struct ndpi_iphdr’
linux_compat.h:57:8: note: originally defined here
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_typedefs.h:210:8: error: redefinition of ‘struct ndpi_in6_addr’
linux_compat.h:138:8: note: originally defined here
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_typedefs.h:225:12: error: redefinition of ‘struct ndpi_ip6_hdrctl’
linux_compat.h:148:12: note: originally defined here
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_typedefs.h:242:8: error: redefinition of ‘struct ndpi_tcphdr’
linux_compat.h:160:8: note: originally defined here
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_typedefs.h:263:8: error: redefinition of ‘struct ndpi_udphdr’
linux_compat.h:177:8: note: originally defined here
pcapReader.c: In function ‘node_proto_guess_walker’:
pcapReader.c:314:26: error: incompatible types when assigning to type ‘u_int32_t’ from type ‘ndpi_protocol’
pcapReader.c: In function ‘packet_processing’:
pcapReader.c:545:14: error: incompatible types when assigning to type ‘u_int32_t’ from type ‘ndpi_protocol’
make: *** [pcapDPI] Error 1

**Comment by siberian1967** [comment]
Same problem here :( The header files have the standard ifndef but its not happy.

**Comment by hichul** [comment]
Thanks it's woking

but it has some warning messages
(ubuntu 16.04)

> make
> gcc -g pcapReader.c -o pcapDPI -I/usr/local/include/libndpi-1.7.0/libndpi -lpcap -lndpi
> pcapReader.c: In function 'packet_processing':
> pcapReader.c:536:5: warning: 'return' with no value, in function returning non-void
>      return;
>      ^
> pcapReader.c:541:33: warning: 'return' with no value, in function returning non-void
>    if(flow->detection_completed) return;
>                                  ^

**Comment by caesar0301** [comment]
Thats Okey. I should be more compatible with gcc specification. ; )

**Comment by hichul** [comment]
Thank you
